# Generated by Django 6.0.4 on 2026-05-24 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("history", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="translationrecord",
            name="source_type",
            field=models.CharField(default="Text", max_length=20),
        ),
    ]
