# Generated by Django 4.2.30 on 2026-05-24 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("history", "0002_translationrecord_source_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="translationrecord",
            name="confidence",
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name="translationrecord",
            name="detected_image",
            field=models.FileField(
                blank=True, null=True, upload_to="detected_gestures/"
            ),
        ),
        migrations.AlterField(
            model_name="translationrecord",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="translations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
